### ISSUE TITLE
Does not launch gtk issue

### ISSUE THREAD

**Issue by CaptainMorgan12** [achhabra2/riftshare#1]
Environment: mobile phone, phosh 0.17.0-1pureos1, 720x1440 screen portrait mode, 200% scaling, riftshare flatpak installed newest release;

Steps to repeat:
1. install magic-wormhole .deb for arm64,
2. install flatpak riftshare,
3. launch app from terminal

Observe app does not launch.

`~$ flatpak run app.riftshare.RiftShare

(RiftShare:2): Gtk-WARNING **: 15:42:30.500: cannot open display:       `

Please modify to make compatible with gnome gtk type environments on mobile.

**Comment by achhabra2** [comment]
Hey thanks for testing out the app and raising this issue. 

Few thoughts here:
1. FWIW I have tested on Linux (Ubuntu, Mint, Manjaro, SteamOS) with no issues. I don't intend on testing on mobile as I don't really have any hardware to test with. If you want to run the tests I'm 100% ok with that, just know that I am not really able to troubleshoot this issue. 
2. You don't need to install magic-wormhole .deb. The Flatpak is meant to be fully self contained. There is no external dependency on the magic-wormhole client. 

Given that it's a GTK issue you're getting I suspect it's actually an issue with the underlying framework that I'm using: [wails](https://wails.io). So we may have to figure out what's going on from that end. 

To rule out that it's not an issue with the way the Flatpak is being built on your system. I would recommend testing by building from source. Please clone the repo and make sure you have go, gcc, libgtk, and libwebkit installed. 

Then clone the repo and run:
```
go install github.com/wailsapp/wails/v2/cmd/wails@latest
wails build  -s
./build/bin/RiftShare
```

See if you get the same error.

**Comment by achhabra2** [comment]
@CaptainMorgan12 I pushed out an update to flathub I think that may fix this issue.  It was probably due to the Wayland desktop session. Would not be an issue building locally, but was an issue when installing from flathub. It will probably take 12-24 hours to show up on flathub.

**Comment by CaptainMorgan12** [comment]
@achhabra2 that fixed the launch issue thanks
