### ISSUE TITLE
Mac available on more regions of the Apple AppStore

### ISSUE THREAD

**Issue by fingolfin** [achhabra2/riftshare#4]
I tried to install RiftShare via the Apple AppStore, but was told that it is not available in my region (the German AppStore).

I have no idea how much effort it would be, but perhaps you could look into making it available in more regions?

Thank you for working on this app!

**Comment by achhabra2** [comment]
Thanks for calling this out. Originally there was some issue with exporting software that contains cryptography / encryption libraries to certain regions. I don't think Germany was on the restricted list, but there were some others so I just kept it to North America. I can open it up to some other regions. 

I actually found a couple of bugs in the app store version -- must be some API changes from the Apple side of things as it used to work fine. I will work on fixing those and update the regions. For now please use the releases from here: https://github.com/achhabra2/riftshare/releases/tag/v0.1.8

Note these releases for MacOS are also code signed and you should not have any issues running it.

**Comment by achhabra2** [comment]
Ok the Mac App Store version has been updated and should be available in other regions now, but I can't very that part from where I live. Please note there is one caveat with using the app store version, if you change the download directory the setting will not persist. 

Let me know if you are able to download it now.

**Comment by fingolfin** [comment]
I can confirm that it is available now in the German store, and I was also able to install and launch it. Have not yet tried to transfer files. 

Thank you!
